# FROM specifies the base image we are extending. 
FROM node:12.18.3-alpine3.9

# Create a directory where our app will be placed:
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the WORKDIR:
COPY package*.json ./

# Install dependencies:
RUN npm install

# Copy app to the container (including the node_modules folder generated by the previous step):
COPY . .

# Expose the port the app runs in:
EXPOSE 3000

# Run the app (in the container):
CMD ["npm", "start"]
